name: analysis
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        run: echo "I am a step where i do sonarcloud things"
