name: deploy

# run this github action on every push
on: [push]

#build and test the next.js project with yarn
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
  conterize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME  }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD  }}
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: echo "Building Docker image"
